name = "8cb7cb64-9066-4eab-a700-eafe841af9d3"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "8.215.18.30"
UUID = "8cb7cb64-9066-4eab-a700-eafe841af9d3"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
